// <auto-generated />
namespace DbFirstApproach.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StringDateOfBirthTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StringDateOfBirthTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202006081721529_StringDateOfBirthTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
